import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10 },
  header: { marginBottom: 16, borderBottom: '1pt solid #e0e0e0', paddingBottom: 8 },
  title: { fontSize: 16, marginBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between' },
  section: { marginTop: 12 },
  label: { color: '#555', marginBottom: 2 },
  table: { display: 'table', width: 'auto', borderStyle: 'solid', borderWidth: 1, borderColor: '#e0e0e0' },
  tableRow: { flexDirection: 'row' },
  tableHeaderCell: { flex: 1, padding: 6, backgroundColor: '#f5f5f5', borderRight: '1pt solid #e0e0e0', fontWeight: 'bold' },
  tableCell: { flex: 1, padding: 6, borderRight: '1pt solid #e0e0e0' }
});

const PrescriptionPDF = ({ prescription }) => {
  const formatDate = (d) => (d ? new Date(d).toLocaleDateString('en-IN') : 'N/A');
  const meds = Array.isArray(prescription?.medications) ? prescription.medications : [];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Prescription</Text>
          <View style={styles.row}>
            <Text>Rx No: {prescription?.prescriptionNumber || 'N/A'}</Text>
            <Text>Date: {formatDate(prescription?.date)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <View>
              <Text style={styles.label}>Patient</Text>
              <Text>{prescription?.patient?.name} {prescription?.patient?.patientId ? `(${prescription.patient.patientId})` : ''}</Text>
              {prescription?.patient?.phone && <Text>Phone: {prescription.patient.phone}</Text>}
            </View>
            <View>
              <Text style={styles.label}>Doctor</Text>
              <Text>Dr. {prescription?.doctor?.name || 'N/A'}</Text>
            </View>
          </View>
        </View>

        {prescription?.diagnosis && (
          <View style={styles.section}>
            <Text style={styles.label}>Diagnosis</Text>
            <Text>{prescription.diagnosis}</Text>
          </View>
        )}

        <View style={{ ...styles.section }}>
          <Text style={styles.label}>Medications</Text>
          <View style={styles.table}>
            <View style={styles.tableRow}>
              <Text style={styles.tableHeaderCell}>Drug</Text>
              <Text style={styles.tableHeaderCell}>Dosage</Text>
              <Text style={styles.tableHeaderCell}>Frequency</Text>
              <Text style={styles.tableHeaderCell}>Duration</Text>
              <Text style={styles.tableHeaderCell}>Instructions</Text>
            </View>
            {meds.map((m, idx) => (
              <View style={styles.tableRow} key={idx}>
                <Text style={styles.tableCell}>{m.drug?.name || ''} {m.strength || ''}</Text>
                <Text style={styles.tableCell}>{m.dosage || ''}</Text>
                <Text style={styles.tableCell}>{m.frequency || ''}</Text>
                <Text style={styles.tableCell}>{m.duration || ''}</Text>
                <Text style={styles.tableCell}>{m.instructions || ''}</Text>
              </View>
            ))}
          </View>
        </View>

        {prescription?.instructions && (
          <View style={styles.section}>
            <Text style={styles.label}>General Instructions</Text>
            <Text>{prescription.instructions}</Text>
          </View>
        )}

        {prescription?.followUpDate && (
          <View style={styles.section}>
            <Text style={styles.label}>Follow-up Date</Text>
            <Text>{formatDate(prescription.followUpDate)}</Text>
          </View>
        )}

        {prescription?.isIssuedToPatient && (
          <View style={styles.section}>
            <Text>Issued to patient on {formatDate(prescription.issuedToPatientDate)} by {prescription?.issuedBy?.name || 'N/A'}</Text>
          </View>
        )}

        <View style={{ ...styles.section, borderTop: '1pt solid #e0e0e0', paddingTop: 8 }}>
          <Text>Generated by DentOS</Text>
        </View>
      </Page>
    </Document>
  );
};

export default PrescriptionPDF;
